"""Community setup gallery (showcase feature): a folder of shared setups people
can browse and adopt with one command, plus an auto-generated index.

Each entry is a `gallery/<name>.share.json` (the share schema + optional
`author`/`description`). `list_entries` parses them and scores each (reusing
score.analyze); `render_index` renders a ranked Markdown table for GALLERY.md.
Adoption reuses the existing `ccpkg apply <path>`.

Stdlib only, Python 3.9.
"""

import json
import os
from typing import Dict, List, Optional

from . import config
from . import score as score_mod
from . import share as share_mod

GALLERY_DIRNAME = "gallery"
INDEX_FILENAME = "GALLERY.md"


def gallery_dir(root=None):
    # type: (Optional[str]) -> str
    return os.path.join(root or config.repo_root(), GALLERY_DIRNAME)


def _entry_files(root):
    # type: (str) -> List[str]
    base = gallery_dir(root)
    if not os.path.isdir(base):
        return []
    return sorted(os.path.join(base, n) for n in os.listdir(base)
                  if n.endswith(".share.json"))


def list_entries(root=None, overlay_present=False):
    # type: (Optional[str], bool) -> List[dict]
    """Parsed + scored gallery entries, ranked by score (desc, then name).
    Malformed files are skipped. Each entry dict: name, author, description,
    file, selected, score, grade, agents, plugins, skills."""
    root = root or config.repo_root()
    files = _entry_files(root)
    if not files:
        return []
    try:
        catalog = share_mod._catalog(root, overlay_present)
    except (OSError, ValueError):
        catalog = {}
    entries = []  # type: List[dict]
    for path in files:
        try:
            with open(path, "r", encoding="utf-8") as fh:
                data = json.load(fh)
        except (OSError, ValueError):
            continue
        if not isinstance(data, dict) or not isinstance(data.get("selected"), list):
            continue
        selected = {str(s) for s in data["selected"]}
        result = score_mod.analyze(selected, catalog)
        fname = os.path.basename(path)
        name = str(data.get("name") or fname[:-len(".share.json")])
        groups = {}  # type: Dict[str, int]
        for sid in selected:
            g = catalog.get(sid, ("", ""))[0]
            groups[g] = groups.get(g, 0) + 1
        entries.append({
            "name": name,
            "author": str(data.get("author") or "—"),
            "description": str(data.get("description") or ""),
            "file": fname,
            "selected": sorted(selected),
            "score": result.score,
            "grade": result.grade,
            "agents": groups.get("Agents", 0),
            "plugins": groups.get("Plugins", 0),
            "skills": groups.get("Skills", 0),
        })
    entries.sort(key=lambda e: (-e["score"], e["name"]))
    return entries


def render_index(root=None, overlay_present=False):
    # type: (Optional[str], bool) -> str
    """A Markdown index of the gallery (ranked table), for GALLERY.md."""
    entries = list_entries(root, overlay_present)
    lines = [
        "# ccpkg setup gallery",
        "",
        "Community Claude Code setups. Adopt any with one command:",
        "",
        "```sh",
        "ccpkg apply gallery/<file>",
        "```",
        "",
        "_This file is generated by `ccpkg gallery index` — edit the "
        "`gallery/*.share.json` files, not this table._",
        "",
        "| Setup | By | Score | Agents | Plugins | Skills | Adopt |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in entries:
        lines.append(
            "| **{name}** — {desc} | {author} | {score}/100 ({grade}) | {agents} "
            "| {plugins} | {skills} | `ccpkg apply gallery/{file}` |".format(
                name=e["name"], desc=e["description"], author=e["author"],
                score=e["score"], grade=e["grade"], agents=e["agents"],
                plugins=e["plugins"], skills=e["skills"], file=e["file"]))
    if not entries:
        lines.append("| _no entries yet_ | | | | | | |")
    lines.append("")
    lines.append("Add yours: drop a `gallery/<name>.share.json` "
                 "(`ccpkg share` makes one), then `ccpkg gallery index`.")
    lines.append("")
    return "\n".join(lines)


def write_index(root=None, overlay_present=False):
    # type: (Optional[str], bool) -> str
    """Render + write GALLERY.md at the repo root. Returns the path."""
    root = root or config.repo_root()
    text = render_index(root, overlay_present)
    path = os.path.join(root, INDEX_FILENAME)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)
    return path
